package Utilities

type LanguageMap struct {
	ISO1 string
	ISO3 []string
}

type LanguageMapping struct {
	LanguageMappings []LanguageMap
}

var LanguageMapList = LanguageMapping{LanguageMappings: []LanguageMap{
	{ISO1: "ace", ISO3: []string{"ace_Arab", "ace_Latn"}},
	{ISO1: "acm", ISO3: []string{"acm_Arab"}},
	{ISO1: "acq", ISO3: []string{"acq_Arab"}},
	{ISO1: "aeb", ISO3: []string{"aeb_Arab"}},
	{ISO1: "af", ISO3: []string{"afr_Latn"}},
	{ISO1: "ajp", ISO3: []string{"ajp_Arab"}},
	{ISO1: "ak", ISO3: []string{"aka_Latn"}},
	{ISO1: "am", ISO3: []string{"amh_Ethi"}},
	{ISO1: "apc", ISO3: []string{"apc_Arab"}},
	{ISO1: "arb", ISO3: []string{"arb_Arab"}},
	{ISO1: "ars", ISO3: []string{"ars_Arab"}},
	{ISO1: "ary", ISO3: []string{"ary_Arab"}},
	{ISO1: "arz", ISO3: []string{"arz_Arab"}},
	{ISO1: "as", ISO3: []string{"asm_Beng"}},
	{ISO1: "ast", ISO3: []string{"ast_Latn"}},
	{ISO1: "awa", ISO3: []string{"awa_Deva"}},
	{ISO1: "ayr", ISO3: []string{"ayr_Latn"}},
	{ISO1: "azb", ISO3: []string{"azb_Arab"}},
	{ISO1: "azj", ISO3: []string{"azj_Latn"}},
	{ISO1: "ba", ISO3: []string{"bak_Cyrl"}},
	{ISO1: "bm", ISO3: []string{"bam_Latn"}},
	{ISO1: "ban", ISO3: []string{"ban_Latn"}},
	{ISO1: "be", ISO3: []string{"bel_Cyrl"}},
	{ISO1: "bem", ISO3: []string{"bem_Latn"}},
	{ISO1: "bn", ISO3: []string{"ben_Beng"}},
	{ISO1: "bho", ISO3: []string{"bho_Deva"}},
	{ISO1: "bjn", ISO3: []string{"bjn_Arab", "bjn_Latn"}},
	{ISO1: "bo", ISO3: []string{"bod_Tibt"}},
	{ISO1: "bs", ISO3: []string{"bos_Latn"}},
	{ISO1: "bug", ISO3: []string{"bug_Latn"}},
	{ISO1: "bg", ISO3: []string{"bul_Cyrl"}},
	{ISO1: "ca", ISO3: []string{"cat_Latn"}},
	{ISO1: "ceb", ISO3: []string{"ceb_Latn"}},
	{ISO1: "cs", ISO3: []string{"ces_Latn"}},
	{ISO1: "cjk", ISO3: []string{"cjk_Latn"}},
	{ISO1: "ckb", ISO3: []string{"ckb_Arab"}},
	{ISO1: "crh", ISO3: []string{"crh_Latn"}},
	{ISO1: "cy", ISO3: []string{"cym_Latn"}},
	{ISO1: "da", ISO3: []string{"dan_Latn"}},
	{ISO1: "de", ISO3: []string{"deu_Latn"}},
	{ISO1: "dik", ISO3: []string{"dik_Latn"}},
	{ISO1: "dyu", ISO3: []string{"dyu_Latn"}},
	{ISO1: "dz", ISO3: []string{"dzo_Tibt"}},
	{ISO1: "el", ISO3: []string{"ell_Grek"}},
	{ISO1: "en", ISO3: []string{"eng_Latn"}},
	{ISO1: "eo", ISO3: []string{"epo_Latn"}},
	{ISO1: "et", ISO3: []string{"est_Latn"}},
	{ISO1: "eu", ISO3: []string{"eus_Latn"}},
	{ISO1: "ee", ISO3: []string{"ewe_Latn"}},
	{ISO1: "fo", ISO3: []string{"fao_Latn"}},
	{ISO1: "pes", ISO3: []string{"pes_Arab"}},
	{ISO1: "fj", ISO3: []string{"fij_Latn"}},
	{ISO1: "fi", ISO3: []string{"fin_Latn"}},
	{ISO1: "fon", ISO3: []string{"fon_Latn"}},
	{ISO1: "fr", ISO3: []string{"fra_Latn"}},
	{ISO1: "fur", ISO3: []string{"fur_Latn"}},
	{ISO1: "fuv", ISO3: []string{"fuv_Latn"}},
	{ISO1: "gd", ISO3: []string{"gla_Latn"}},
	{ISO1: "ga", ISO3: []string{"gle_Latn"}},
	{ISO1: "gl", ISO3: []string{"glg_Latn"}},
	{ISO1: "gn", ISO3: []string{"grn_Latn"}},
	{ISO1: "gu", ISO3: []string{"guj_Gujr"}},
	{ISO1: "ht", ISO3: []string{"hat_Latn"}},
	{ISO1: "ha", ISO3: []string{"hau_Latn"}},
	{ISO1: "he", ISO3: []string{"heb_Hebr"}},
	{ISO1: "hi", ISO3: []string{"hin_Deva"}},
	{ISO1: "hne", ISO3: []string{"hne_Deva"}},
	{ISO1: "hr", ISO3: []string{"hrv_Latn"}},
	{ISO1: "hu", ISO3: []string{"hun_Latn"}},
	{ISO1: "hy", ISO3: []string{"hye_Armn"}},
	{ISO1: "ig", ISO3: []string{"ibo_Latn"}},
	{ISO1: "ilo", ISO3: []string{"ilo_Latn"}},
	{ISO1: "id", ISO3: []string{"ind_Latn"}},
	{ISO1: "is", ISO3: []string{"isl_Latn"}},
	{ISO1: "it", ISO3: []string{"ita_Latn"}},
	{ISO1: "jv", ISO3: []string{"jav_Latn"}},
	{ISO1: "ja", ISO3: []string{"jpn_Jpan"}},
	{ISO1: "kab", ISO3: []string{"kab_Latn"}},
	{ISO1: "kac", ISO3: []string{"kac_Latn"}},
	{ISO1: "kam", ISO3: []string{"kam_Latn"}},
	{ISO1: "kn", ISO3: []string{"kan_Knda"}},
	{ISO1: "ks", ISO3: []string{"kas_Arab", "kas_Deva"}},
	{ISO1: "ka", ISO3: []string{"kat_Geor"}},
	{ISO1: "knc", ISO3: []string{"knc_Arab", "knc_Latn"}},
	{ISO1: "kk", ISO3: []string{"kaz_Cyrl"}},
	{ISO1: "kbp", ISO3: []string{"kbp_Latn"}},
	{ISO1: "kea", ISO3: []string{"kea_Latn"}},
	{ISO1: "km", ISO3: []string{"khm_Khmr"}},
	{ISO1: "ki", ISO3: []string{"kik_Latn"}},
	{ISO1: "rw", ISO3: []string{"kin_Latn"}},
	{ISO1: "ky", ISO3: []string{"kir_Cyrl"}},
	{ISO1: "kmb", ISO3: []string{"kmb_Latn"}},
	{ISO1: "kg", ISO3: []string{"kon_Latn"}},
	{ISO1: "ko", ISO3: []string{"kor_Hang"}},
	{ISO1: "kmr", ISO3: []string{"kmr_Latn"}},
	{ISO1: "lo", ISO3: []string{"lao_Laoo"}},
	{ISO1: "lvs", ISO3: []string{"lvs_Latn"}},
	{ISO1: "lij", ISO3: []string{"lij_Latn"}},
	{ISO1: "li", ISO3: []string{"lim_Latn"}},
	{ISO1: "ln", ISO3: []string{"lin_Latn"}},
	{ISO1: "lt", ISO3: []string{"lit_Latn"}},
	{ISO1: "lmo", ISO3: []string{"lmo_Latn"}},
	{ISO1: "ltg", ISO3: []string{"ltg_Latn"}},
	{ISO1: "lb", ISO3: []string{"ltz_Latn"}},
	{ISO1: "lua", ISO3: []string{"lua_Latn"}},
	{ISO1: "lg", ISO3: []string{"lug_Latn"}},
	{ISO1: "luo", ISO3: []string{"luo_Latn"}},
	{ISO1: "lus", ISO3: []string{"lus_Latn"}},
	{ISO1: "mag", ISO3: []string{"mag_Deva"}},
	{ISO1: "mai", ISO3: []string{"mai_Deva"}},
	{ISO1: "ml", ISO3: []string{"mal_Mlym"}},
	{ISO1: "mr", ISO3: []string{"mar_Deva"}},
	{ISO1: "min", ISO3: []string{"min_Latn"}},
	{ISO1: "mk", ISO3: []string{"mkd_Cyrl"}},
	{ISO1: "plt", ISO3: []string{"plt_Latn"}},
	{ISO1: "mt", ISO3: []string{"mlt_Latn"}},
	{ISO1: "mni", ISO3: []string{"mni_Beng"}},
	{ISO1: "khk", ISO3: []string{"khk_Cyrl"}},
	{ISO1: "mos", ISO3: []string{"mos_Latn"}},
	{ISO1: "mi", ISO3: []string{"mri_Latn"}},
	{ISO1: "zsm", ISO3: []string{"zsm_Latn"}},
	{ISO1: "my", ISO3: []string{"mya_Mymr"}},
	{ISO1: "nl", ISO3: []string{"nld_Latn"}},
	{ISO1: "nn", ISO3: []string{"nno_Latn"}},
	{ISO1: "nb", ISO3: []string{"nob_Latn"}},
	{ISO1: "npi", ISO3: []string{"npi_Deva"}},
	{ISO1: "nso", ISO3: []string{"nso_Latn"}},
	{ISO1: "nus", ISO3: []string{"nus_Latn"}},
	{ISO1: "ny", ISO3: []string{"nya_Latn"}},
	{ISO1: "oc", ISO3: []string{"oci_Latn"}},
	{ISO1: "gaz", ISO3: []string{"gaz_Latn"}},
	{ISO1: "ory", ISO3: []string{"ory_Orya"}},
	{ISO1: "pag", ISO3: []string{"pag_Latn"}},
	{ISO1: "pa", ISO3: []string{"pan_Guru"}},
	{ISO1: "pap", ISO3: []string{"pap_Latn"}},
	{ISO1: "pl", ISO3: []string{"pol_Latn"}},
	{ISO1: "pt", ISO3: []string{"por_Latn"}},
	{ISO1: "prs", ISO3: []string{"prs_Arab"}},
	{ISO1: "pbt", ISO3: []string{"pbt_Arab"}},
	{ISO1: "quy", ISO3: []string{"quy_Latn"}},
	{ISO1: "ro", ISO3: []string{"ron_Latn"}},
	{ISO1: "rn", ISO3: []string{"run_Latn"}},
	{ISO1: "ru", ISO3: []string{"rus_Cyrl"}},
	{ISO1: "sg", ISO3: []string{"sag_Latn"}},
	{ISO1: "sa", ISO3: []string{"san_Deva"}},
	{ISO1: "sat", ISO3: []string{"sat_Beng"}},
	{ISO1: "scn", ISO3: []string{"scn_Latn"}},
	{ISO1: "shn", ISO3: []string{"shn_Mymr"}},
	{ISO1: "si", ISO3: []string{"sin_Sinh"}},
	{ISO1: "sk", ISO3: []string{"slk_Latn"}},
	{ISO1: "sl", ISO3: []string{"slv_Latn"}},
	{ISO1: "sm", ISO3: []string{"smo_Latn"}},
	{ISO1: "sn", ISO3: []string{"sna_Latn"}},
	{ISO1: "sd", ISO3: []string{"snd_Arab"}},
	{ISO1: "so", ISO3: []string{"som_Latn"}},
	{ISO1: "st", ISO3: []string{"sot_Latn"}},
	{ISO1: "es", ISO3: []string{"spa_Latn"}},
	{ISO1: "als", ISO3: []string{"als_Latn"}},
	{ISO1: "sc", ISO3: []string{"srd_Latn"}},
	{ISO1: "sr", ISO3: []string{"srp_Cyrl"}},
	{ISO1: "ss", ISO3: []string{"ssw_Latn"}},
	{ISO1: "su", ISO3: []string{"sun_Latn"}},
	{ISO1: "sv", ISO3: []string{"swe_Latn"}},
	{ISO1: "swh", ISO3: []string{"swh_Latn"}},
	{ISO1: "szl", ISO3: []string{"szl_Latn"}},
	{ISO1: "ta", ISO3: []string{"tam_Taml"}},
	{ISO1: "tt", ISO3: []string{"tat_Cyrl"}},
	{ISO1: "te", ISO3: []string{"tel_Telu"}},
	{ISO1: "tg", ISO3: []string{"tgk_Cyrl"}},
	{ISO1: "tl", ISO3: []string{"tgl_Latn"}},
	{ISO1: "th", ISO3: []string{"tha_Thai"}},
	{ISO1: "ti", ISO3: []string{"tir_Ethi"}},
	{ISO1: "taq", ISO3: []string{"taq_Tfng", "taq_Latn"}},
	{ISO1: "tpi", ISO3: []string{"tpi_Latn"}},
	{ISO1: "tn", ISO3: []string{"tsn_Latn"}},
	{ISO1: "ts", ISO3: []string{"tso_Latn"}},
	{ISO1: "tk", ISO3: []string{"tuk_Latn"}},
	{ISO1: "tum", ISO3: []string{"tum_Latn"}},
	{ISO1: "tr", ISO3: []string{"tur_Latn"}},
	{ISO1: "tw", ISO3: []string{"twi_Latn"}},
	{ISO1: "tzm", ISO3: []string{"tzm_Tfng"}},
	{ISO1: "ug", ISO3: []string{"uig_Arab"}},
	{ISO1: "uk", ISO3: []string{"ukr_Cyrl"}},
	{ISO1: "umb", ISO3: []string{"umb_Latn"}},
	{ISO1: "ur", ISO3: []string{"urd_Arab"}},
	{ISO1: "uzn", ISO3: []string{"uzn_Latn"}},
	{ISO1: "vec", ISO3: []string{"vec_Latn"}},
	{ISO1: "vi", ISO3: []string{"vie_Latn"}},
	{ISO1: "war", ISO3: []string{"war_Latn"}},
	{ISO1: "wo", ISO3: []string{"wol_Latn"}},
	{ISO1: "xh", ISO3: []string{"xho_Latn"}},
	{ISO1: "ydd", ISO3: []string{"ydd_Hebr"}},
	{ISO1: "yo", ISO3: []string{"yor_Latn"}},
	{ISO1: "yue", ISO3: []string{"yue_Hant"}},
	{ISO1: "zh", ISO3: []string{"zho_Hans", "zho_Hant"}},
	{ISO1: "zu", ISO3: []string{"zul_Latn"}},
}}

func (languageMapping *LanguageMap) GetISO1() string {
	return languageMapping.ISO1
}

func (languageMapping *LanguageMap) GetISO3() []string {
	return languageMapping.ISO3
}

func (languageMapping *LanguageMapping) GetISO3(iso1 string) []string {
	for _, languageMap := range languageMapping.LanguageMappings {
		if languageMap.ISO1 == iso1 {
			return languageMap.GetISO3()
		}
	}
	return []string{}
}

func (languageMapping *LanguageMapping) GetISO1(iso3 string) string {
	for _, languageMap := range languageMapping.LanguageMappings {
		for _, languageIso3 := range languageMap.ISO3 {
			if languageIso3 == iso3 {
				return languageMap.GetISO1()
			}
		}
	}
	return ""
}
